import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "ru" | "en";

const translations = {
  ru: {
    nav: {
      services: "Услуги",
      marketplaces: "Маркетплейсы",
      sites: "Сайты",
      logos: "Логотипы",
      portfolio: "Портфолио",
      blog: "Блог",
      contacts: "Контакты",
    },
    hero: {
      title: "Дизайн для бизнеса\nчерез нейросети",
      sub1: "Карточки товаров\u00a0•\u00a0Сайты\u00a0•\u00a0Меню для кафе",
      sub2: "Обложки ВК\u00a0•\u00a0Визуал для соцсетей\u00a0•\u00a0Брендинг",
      tagline: "Быстрее фрилансера.\u00a0Дешевле агентства.\u00a0Круче шаблонов.",
      cta: "Обсудить проект",
      portfolio: "Смотреть портфолио",
    },
    about: {
      tag: "ОБО МНЕ",
      title: "Привет! Меня зовут Стрельцов Иван",
      p1: "Делаю дизайн для бизнеса с помощью нейросетей.",
      p2_pre: "Пока другие тратят",
      p2_bold1: "100–300к на агентства",
      p2_mid: "и ждут месяц — мои клиенты получают результат за",
      p2_bold2: "2–3 дня в 5 раз дешевле.",
      p3: "AI не заменяет дизайнера. AI — это инструмент в руках дизайнера. ",
      p3_bold: "И я знаю как им пользоваться.",
    },
    services: {
      tag: "Что я делаю",
      title: "УСЛУГИ",
      items: [
        { title: "Карточки для маркетплейсов", desc: "Продающие фото и инфографика для Ozon, Wildberries, Яндекс Маркет", price: "от 1 990₽" },
        { title: "Сайты через нейросети", desc: "Лендинги и многостраничники с AI-дизайном за 2–3 дня", price: "от 14 000₽" },
        { title: "Меню для кафе на ТВ-экраны", desc: "Электронные меню-борды для любого заведения", price: "от 2 990₽" },
        { title: "Обложки для групп ВК", desc: "Профессиональные баннеры, которые выделяют среди конкурентов", price: "от 1 990₽" },
        { title: "Визуал для соцсетей", desc: "Контент-паки 8–15 фото в едином стиле для любой ниши", price: "от 2 990₽" },
        { title: "Логотипы и брендинг", desc: "Логотип + фирменный стиль + визитки + упаковка", price: "от 4 990₽" },
        { title: "Видео-контент", desc: "AI-клипы для рилс и клипов ВК, 10–30 секунд", price: "от 3 990₽" },
        { title: "Дизайн для кафе под ключ", desc: "Меню + вывеска + соцсети + упаковка + карта лояльности", price: "от 9 990₽" },
      ],
    },
    how: {
      tag: "Процесс",
      title: "Как я работаю",
      steps: [
        { title: "ПИШЕТЕ МНЕ", desc: "Рассказываете что нужно — сайт, карточки, меню или обложку" },
        { title: "БЕСПЛАТНЫЙ МАКЕТ ЗА 24 ЧАСА", desc: "Показываю первый вариант — если не нравится, не платите" },
        { title: "ДОДЕЛЫВАЮ И ОТДАЮ", desc: "Вношу правки, финализирую и отдаю готовые файлы" },
      ],
    },
    stats: {
      tag: "Результаты",
      title: "В цифрах",
      items: [
        { value: "50+", label: "проектов" },
        { value: "15+", label: "ниш бизнеса" },
        { value: "24 ч", label: "первый макет" },
        { value: "5×", label: "дешевле агентства" },
      ],
    },
    portfolio: {
      tag: "Портфолио",
      title: "МОИ РАБОТЫ",
      filters: ["Все", "Маркетплейсы", "Сайты", "Меню кафе", "Обложки ВК", "Визуал", "Брендинг"],
    },
    faq: {
      tag: "FAQ",
      title: "Частые вопросы",
      items: [
        { q: "Это реальные фото или нейросеть?", a: "Генерирую нейросетью и дорабатываю. Не отличить от профессиональной съёмки." },
        { q: "Сколько времени занимает сайт?", a: "Лендинг — 2–3 дня. Многостраничный — 5–7 дней." },
        { q: "На чём делаете сайты?", a: "На нейро платформах." },
        { q: "А если не понравится?", a: "Макет бесплатный. Не нравится — не платите." },
        { q: "Можно ли вносить правки?", a: "До 3 правок включены в стоимость." },
      ],
    },
    contact: {
      tag: "Контакты",
      title: "Обсудить проект",
      sub: "Напишите мне — покажу бесплатный макет\nпод ваш бизнес за 24 часа",
      vk: "Написать в ВК",
      tg: "Написать в Telegram",
    },
    footer: {
      tagline: "Дизайн для бизнеса через нейросети.\nБыстрее фрилансера, дешевле агентства.",
      services: "Услуги",
      nav: "Навигация",
      copyright: "Все права защищены",
      slogan: "Дизайн через нейросети · Быстро · Качественно · Доступно",
      serviceItems: [
        { label: "Карточки для маркетплейсов", href: "#маркетплейсы" },
        { label: "Сайты через нейросети", href: "#сайты" },
        { label: "Обложки для ВК", href: "#обложки" },
        { label: "Логотипы и брендинг", href: "#логотипы" },
        { label: "Меню для кафе", href: "#услуги" },
      ],
      navItems: [
        { label: "Портфолио", href: "#портфолио" },
        { label: "Обо мне", href: "#о нас" },
        { label: "Блог", href: "/blog" },
        { label: "Контакты", href: "#контакты" },
      ],
    },
    vkBanner: {
      desc: "Дизайн для бизнеса · Визуал · Брендинг",
      follow: "Подписаться",
    },
    websites: {
      tag: "Услуга",
      title: "🌐 Делаю сайты\nчерез нейросети",
      sub: "Не шаблон. Не конструктор. Уникальный AI-дизайн.",
      benefitsTitle: "Что получаете",
      benefits: [
        "Уникальный дизайн — не похож ни на кого",
        "Адаптив — работает на телефоне и компьютере",
        "Быстро — готово за 2–3 дня",
        "Тексты — пишу продающие тексты",
        "Фото — генерирую через нейросеть под ваш бизнес",
      ],
      typesTitle: "Какие сайты делаю",
      types: [
        { emoji: "📱", title: "Визитка (3–5 стр.)", price: "14 000–20 000₽", desc: "Главная, услуги, о нас, контакты", term: "до 5 дней" },
        { emoji: "🏢", title: "Бизнес-сайт (10–20 стр.)", price: "35 000–50 000₽", desc: "Имидж и детальное описание каждого направления", term: "1–2 недели" },
        { emoji: "🗂️", title: "Каталог (20+ стр.)", price: "от 80 000₽", desc: "База товаров или услуг с удобной навигацией", term: "от 14 дней" },
      ],
      includedTitle: "В каждый проект входит",
      included: [
        "Адаптация под мобильные устройства",
        "Генерация уникального контента через ИИ",
        "Проф SEO-оптимизация",
      ],
      forWhomTitle: "Для кого",
      clients: [
        { emoji: "☕", label: "Кафе и рестораны" },
        { emoji: "💈", label: "Барбершопы и салоны красоты" },
        { emoji: "🏋️", label: "Фитнес-клубы и тренеры" },
        { emoji: "🌸", label: "Цветочные магазины" },
        { emoji: "🏠", label: "Строительные компании" },
        { emoji: "👗", label: "Шоурумы и бренды одежды" },
        { emoji: "📚", label: "Онлайн-школы" },
        { emoji: "🔧", label: "Услуги любые" },
      ],
      termLabel: "Срок:",
      cta: "Хочу сайт → Написать в ЛС",
      ctaMsg: "Хочу заказать сайт через нейросети",
    },
    marketCards: {
      tag: "Услуга",
      title: "📦 Карточки товаров\nдля маркетплейсов",
      sub1: "Продающие карточки для",
      sub2: "Скучная карточка = листают дальше.",
      sub3: "Яркая = кликают и покупают.",
      popular: "Хит",
      packages: [
        { title: "1 карточка", price: "1 990₽", items: ["1 главный слайд", "Инфографика", "2 правки"] },
        { title: "3 карточки", price: "4 990₽", items: ["Главная + 2 доп. слайда", "Продающие блоки", "3–4 правки"], popular: true },
        { title: "5 карточек", price: "7 990₽", items: ["Полный комплект", "Структура под маркетплейс", "Инфографика", "Все исходники"] },
      ],
      benefitsTitle: "Что входит в каждую карточку",
      benefits: [
        "Главный слайд — цепляет взгляд в выдаче",
        "Инфографика — свойства и преимущества",
        "Продающие блоки — закрывают возражения",
        "Исходники — редактируйте сами",
      ],
      nichesTitle: "Примеры ниш",
      niches: [
        { emoji: "👟", label: "Обувь", desc: "ракурсы, размерная сетка, материал" },
        { emoji: "💄", label: "Косметика", desc: "состав, до/после, применение" },
        { emoji: "🔧", label: "Инструменты", desc: "характеристики, комплектация" },
        { emoji: "👗", label: "Одежда", desc: "ткань, посадка, размеры" },
        { emoji: "🍵", label: "Еда и напитки", desc: "состав, вкус, упаковка" },
        { emoji: "🏠", label: "Товары для дома", desc: "размеры, материал, применение" },
      ],
      cta: "Хочу карточки → Написать в ЛС",
      ctaMsg: "Хочу заказать карточки товаров для маркетплейса",
    },
    vkCovers: {
      tag: "Услуга",
      title: "🎨 Обложки для групп ВК",
      sub1: "Первое что видит человек заходя в группу — обложка.",
      sub2: "Скучная обложка = ушёл.",
      sub3: "Яркая обложка = подписался.",
      benefitsTitle: "Что делаю",
      benefits: [
        "Статичные обложки — 1 картинка",
        "Живые обложки — 5 сменяющихся картинок",
        "Под любую нишу и стиль",
        "С текстом, акциями, контактами",
      ],
      nichesTitle: "Примеры ниш",
      niches: [
        { emoji: "☕", label: "Кофейня", desc: "тёплые тона, латте-арт, уют" },
        { emoji: "💈", label: "Барбершоп", desc: "тёмный стиль, мужской вайб" },
        { emoji: "🍕", label: "Пиццерия", desc: "аппетитная пицца с тянущимся сыром" },
        { emoji: "💅", label: "Nail-мастер", desc: "нежные тона, ногти, цветы" },
        { emoji: "🏋️", label: "Фитнес", desc: "мощный, энергичный, мотивация" },
        { emoji: "🌸", label: "Цветы", desc: "нежный, романтичный" },
      ],
      pricesTitle: "Цены",
      prices: [
        { title: "Простая обложка", price: "1 990₽", desc: "чистый дизайн, текст, контакты" },
        { title: "Сложная графика", price: "2 990₽", desc: "детальная иллюстрация, эффекты" },
        { title: "Премиум стиль", price: "3 990₽", desc: "уникальный дизайн под бренд" },
      ],
      cta: "Хочу обложку → Написать в ЛС",
      ctaMsg: "Хочу заказать обложку для группы ВКонтакте",
    },
    logos: {
      tag: "Брендинг",
      title: "⚡ Логотипы и Брендинг",
      sub1: "Не шаблон из конструктора. Не клипарт.",
      sub2: "Уникальный логотип через нейросети",
      sub3: " за 1 день.",
      popular: "Популярный",
      packages: [
        { title: "Старт", price: "2 990₽", items: ["1 концепция", "2 правки", "PNG + JPG"] },
        { title: "Бизнес", price: "5 990₽", items: ["2 концепции", "5 правок", "PNG + JPG + PDF + SVG", "Подбор цветов и шрифтов"], popular: true },
        { title: "Премиум", price: "9 990₽", items: ["3 концепции", "Неограниченные правки", "Все форматы", "Адаптация под маркетплейсы"] },
      ],
      nichesTitle: "Примеры ниш",
      niches: [
        { emoji: "☕", label: "Кофейня", desc: "тёплые тона, минимализм" },
        { emoji: "💈", label: "Барбершоп", desc: "мужской стиль, брутал" },
        { emoji: "🍕", label: "Ресторан / кафе", desc: "аппетитно и узнаваемо" },
        { emoji: "💅", label: "Бьюти-студия", desc: "нежно, стильно, женственно" },
        { emoji: "🏋️", label: "Фитнес / спорт", desc: "энергия, динамика, сила" },
        { emoji: "🔧", label: "Услуги / ремонт", desc: "надёжно, профессионально" },
      ],
      cta: "Хочу логотип → Написать в ЛС",
      ctaMsg: "Хочу заказать логотип и брендинг",
    },
    social: {
      tag: "Соцсети",
      title: "Визуал для соцсетей",
      sub: "Готовый контент-пак для ВК, Telegram и соцсетей",
      desc: "Ваша лента будет выглядеть как у крупного бренда.\n8–15 фото в едином стиле. Посты, сторис, баннеры.\nВыложил — и подписчики думают что у вас SMM-отдел.",
      bullets: [
        "8–15 фото в едином стиле",
        "Посты + сторис + баннеры акций",
        "Под вашу нишу и фирменные цвета",
        "Готово к публикации — просто выкладывай",
        "Контент-план + тексты в пакете Премиум",
      ],
      popular: "Популярный",
      plans: [
        { name: "Визуал Лайт", price: "2 990₽", features: ["8 фото в едином стиле", "Квадратный формат 1:1", "Для ВК или Telegram"] },
        { name: "Визуал Стандарт", price: "4 990₽", popular: true, features: ["12 фото в едином стиле", "Квадрат 1:1 + сторис 9:16", "2 баннера для акций", "Для ВК и Telegram"] },
        { name: "Визуал Премиум", price: "7 990₽", features: ["15 фото + 5 сторис", "3 баннера для акций", "Контент-план на месяц", "Тексты к каждому посту", "Хештеги"] },
      ],
      orderBtn: "Заказать",
    },
    blog: {
      tag: "Стрельцов Digital",
      title: "БЛОГ",
      sub: "Статьи о дизайне, нейросетях и бизнесе",
      filters: ["Все", "Дизайн", "Нейросети", "Маркетплейсы", "Кафе", "Брендинг", "Кейс", "Гайд"],
      readMore: "Читать →",
      minRead: "мин",
      loadMore: "Загрузить ещё статьи",
    },
  },
  en: {
    nav: {
      services: "Services",
      marketplaces: "Marketplaces",
      sites: "Websites",
      logos: "Logos",
      portfolio: "Portfolio",
      blog: "Blog",
      contacts: "Contacts",
    },
    hero: {
      title: "Business Design\nPowered by AI",
      sub1: "Product Cards\u00a0•\u00a0Websites\u00a0•\u00a0Cafe Menus",
      sub2: "VK Covers\u00a0•\u00a0Social Visuals\u00a0•\u00a0Branding",
      tagline: "Faster than a freelancer.\u00a0Cheaper than an agency.\u00a0Better than templates.",
      cta: "Discuss a project",
      portfolio: "View portfolio",
    },
    about: {
      tag: "ABOUT ME",
      title: "Hi! My name is Ivan Streltsov",
      p1: "I create business design using AI tools.",
      p2_pre: "While others spend",
      p2_bold1: "100–300k on agencies",
      p2_mid: "and wait a month — my clients get results in",
      p2_bold2: "2–3 days at 5x lower cost.",
      p3: "AI doesn't replace a designer. AI is a tool in a designer's hands. ",
      p3_bold: "And I know how to use it.",
    },
    services: {
      tag: "What I do",
      title: "SERVICES",
      items: [
        { title: "Marketplace Product Cards", desc: "Selling photos & infographics for Ozon, Wildberries, Yandex Market", price: "from ₽1,990" },
        { title: "AI-Powered Websites", desc: "Landing pages & multi-page sites with AI design in 2–3 days", price: "from ₽14,000" },
        { title: "Cafe TV Menu Boards", desc: "Digital menu boards for any food establishment", price: "from ₽2,990" },
        { title: "VK Group Covers", desc: "Professional banners that stand out from competitors", price: "from ₽1,990" },
        { title: "Social Media Visuals", desc: "Content packs of 8–15 photos in one unified style for any niche", price: "from ₽2,990" },
        { title: "Logos & Branding", desc: "Logo + corporate identity + business cards + packaging", price: "from ₽4,990" },
        { title: "Video Content", desc: "AI clips for reels and VK videos, 10–30 seconds", price: "from ₽3,990" },
        { title: "Cafe Design Turnkey", desc: "Menu + signage + social media + packaging + loyalty card", price: "from ₽9,990" },
      ],
    },
    how: {
      tag: "Process",
      title: "How I work",
      steps: [
        { title: "CONTACT ME", desc: "Tell me what you need — a website, product cards, menu or cover" },
        { title: "FREE MOCKUP IN 24 HOURS", desc: "I show the first version — if you don't like it, you don't pay" },
        { title: "FINISH & DELIVER", desc: "I make edits, finalize and deliver the ready files" },
      ],
    },
    stats: {
      tag: "Results",
      title: "By the numbers",
      items: [
        { value: "50+", label: "projects" },
        { value: "15+", label: "business niches" },
        { value: "24h", label: "first mockup" },
        { value: "5×", label: "cheaper than agency" },
      ],
    },
    portfolio: {
      tag: "Portfolio",
      title: "MY WORKS",
      filters: ["All", "Marketplaces", "Websites", "Cafe Menu", "VK Covers", "Visuals", "Branding"],
    },
    faq: {
      tag: "FAQ",
      title: "Frequently Asked Questions",
      items: [
        { q: "Are these real photos or AI-generated?", a: "I generate with AI and refine. Indistinguishable from professional photography." },
        { q: "How long does a website take?", a: "A landing page — 2–3 days. Multi-page — 5–7 days." },
        { q: "What platform do you build sites on?", a: "On AI platforms." },
        { q: "What if I don't like it?", a: "The mockup is free. If you don't like it — you don't pay." },
        { q: "Can I request revisions?", a: "Up to 3 revisions are included in the price." },
      ],
    },
    contact: {
      tag: "Contacts",
      title: "Discuss a project",
      sub: "Write to me — I'll show a free mockup\ntailored to your business in 24 hours",
      vk: "Message on VK",
      tg: "Message on Telegram",
    },
    footer: {
      tagline: "Business design powered by AI.\nFaster than a freelancer, cheaper than an agency.",
      services: "Services",
      nav: "Navigation",
      copyright: "All rights reserved",
      slogan: "AI Design · Fast · Quality · Affordable",
      serviceItems: [
        { label: "Marketplace Cards", href: "#маркетплейсы" },
        { label: "AI Websites", href: "#сайты" },
        { label: "VK Covers", href: "#обложки" },
        { label: "Logos & Branding", href: "#логотипы" },
        { label: "Cafe Menus", href: "#услуги" },
      ],
      navItems: [
        { label: "Portfolio", href: "#портфолио" },
        { label: "About me", href: "#о нас" },
        { label: "Blog", href: "/blog" },
        { label: "Contacts", href: "#контакты" },
      ],
    },
    vkBanner: {
      desc: "Business Design · Visuals · Branding",
      follow: "Follow",
    },
    websites: {
      tag: "Service",
      title: "🌐 AI-Powered\nWebsites",
      sub: "Not a template. Not a builder. Unique AI design.",
      benefitsTitle: "What you get",
      benefits: [
        "Unique design — like no one else",
        "Responsive — works on mobile and desktop",
        "Fast — ready in 2–3 days",
        "Copywriting — I write selling texts",
        "Photos — AI-generated for your business",
      ],
      typesTitle: "Types of sites I build",
      types: [
        { emoji: "📱", title: "Business Card (3–5 pages)", price: "₽14,000–20,000", desc: "Home, services, about us, contacts", term: "up to 5 days" },
        { emoji: "🏢", title: "Business Site (10–20 pages)", price: "₽35,000–50,000", desc: "Image and detailed description of each direction", term: "1–2 weeks" },
        { emoji: "🗂️", title: "Catalog (20+ pages)", price: "from ₽80,000", desc: "Product or service database with easy navigation", term: "from 14 days" },
      ],
      includedTitle: "Every project includes",
      included: [
        "Mobile device adaptation",
        "Unique AI-generated content",
        "Professional SEO optimization",
      ],
      forWhomTitle: "Who it's for",
      clients: [
        { emoji: "☕", label: "Cafes & restaurants" },
        { emoji: "💈", label: "Barbershops & beauty salons" },
        { emoji: "🏋️", label: "Fitness clubs & trainers" },
        { emoji: "🌸", label: "Flower shops" },
        { emoji: "🏠", label: "Construction companies" },
        { emoji: "👗", label: "Showrooms & clothing brands" },
        { emoji: "📚", label: "Online schools" },
        { emoji: "🔧", label: "Any services" },
      ],
      termLabel: "Timeline:",
      cta: "I want a site → Message me",
      ctaMsg: "I want to order an AI-powered website",
    },
    marketCards: {
      tag: "Service",
      title: "📦 Product Cards\nfor Marketplaces",
      sub1: "Selling cards for",
      sub2: "Boring card = they scroll past.",
      sub3: "Eye-catching = they click and buy.",
      popular: "Hit",
      packages: [
        { title: "1 card", price: "₽1,990", items: ["1 main slide", "Infographics", "2 revisions"] },
        { title: "3 cards", price: "₽4,990", items: ["Main + 2 extra slides", "Selling blocks", "3–4 revisions"], popular: true },
        { title: "5 cards", price: "₽7,990", items: ["Full set", "Marketplace structure", "Infographics", "All source files"] },
      ],
      benefitsTitle: "What's in each card",
      benefits: [
        "Main slide — catches the eye in search",
        "Infographics — features and advantages",
        "Selling blocks — handle objections",
        "Source files — edit yourself",
      ],
      nichesTitle: "Niche examples",
      niches: [
        { emoji: "👟", label: "Footwear", desc: "angles, size chart, material" },
        { emoji: "💄", label: "Cosmetics", desc: "ingredients, before/after, how to use" },
        { emoji: "🔧", label: "Tools", desc: "specs, kit contents" },
        { emoji: "👗", label: "Clothing", desc: "fabric, fit, sizes" },
        { emoji: "🍵", label: "Food & drinks", desc: "ingredients, taste, packaging" },
        { emoji: "🏠", label: "Home goods", desc: "dimensions, material, use" },
      ],
      cta: "I want cards → Message me",
      ctaMsg: "I want to order marketplace product cards",
    },
    vkCovers: {
      tag: "Service",
      title: "🎨 VK Group Covers",
      sub1: "The first thing a person sees when entering a group — the cover.",
      sub2: "Boring cover = they leave.",
      sub3: "Eye-catching cover = they subscribe.",
      benefitsTitle: "What I do",
      benefits: [
        "Static covers — 1 image",
        "Live covers — 5 rotating images",
        "For any niche and style",
        "With text, promos, contacts",
      ],
      nichesTitle: "Niche examples",
      niches: [
        { emoji: "☕", label: "Coffee shop", desc: "warm tones, latte art, cozy" },
        { emoji: "💈", label: "Barbershop", desc: "dark style, masculine vibe" },
        { emoji: "🍕", label: "Pizzeria", desc: "appetizing pizza with melting cheese" },
        { emoji: "💅", label: "Nail master", desc: "soft tones, nails, flowers" },
        { emoji: "🏋️", label: "Fitness", desc: "powerful, energetic, motivating" },
        { emoji: "🌸", label: "Flowers", desc: "gentle, romantic" },
      ],
      pricesTitle: "Prices",
      prices: [
        { title: "Simple cover", price: "₽1,990", desc: "clean design, text, contacts" },
        { title: "Complex graphics", price: "₽2,990", desc: "detailed illustration, effects" },
        { title: "Premium style", price: "₽3,990", desc: "unique design for your brand" },
      ],
      cta: "I want a cover → Message me",
      ctaMsg: "I want to order a VK group cover",
    },
    logos: {
      tag: "Branding",
      title: "⚡ Logos & Branding",
      sub1: "Not a template. Not a clipart.",
      sub2: "Unique AI-powered logo",
      sub3: " in 1 day.",
      popular: "Popular",
      packages: [
        { title: "Start", price: "₽2,990", items: ["1 concept", "2 revisions", "PNG + JPG"] },
        { title: "Business", price: "₽5,990", items: ["2 concepts", "5 revisions", "PNG + JPG + PDF + SVG", "Color & font selection"], popular: true },
        { title: "Premium", price: "₽9,990", items: ["3 concepts", "Unlimited revisions", "All formats", "Marketplace adaptation"] },
      ],
      nichesTitle: "Niche examples",
      niches: [
        { emoji: "☕", label: "Coffee shop", desc: "warm tones, minimalism" },
        { emoji: "💈", label: "Barbershop", desc: "masculine style, brutal" },
        { emoji: "🍕", label: "Restaurant / cafe", desc: "appetizing and recognizable" },
        { emoji: "💅", label: "Beauty studio", desc: "gentle, stylish, feminine" },
        { emoji: "🏋️", label: "Fitness / sports", desc: "energy, dynamics, power" },
        { emoji: "🔧", label: "Services / repair", desc: "reliable, professional" },
      ],
      cta: "I want a logo → Message me",
      ctaMsg: "I want to order a logo and branding",
    },
    social: {
      tag: "Social Media",
      title: "Social Media Visuals",
      sub: "Ready content pack for VK, Telegram and social media",
      desc: "Your feed will look like a major brand.\n8–15 photos in one unified style. Posts, stories, banners.\nPost it — and followers will think you have an SMM team.",
      bullets: [
        "8–15 photos in unified style",
        "Posts + stories + promo banners",
        "For your niche and brand colors",
        "Ready to publish — just post it",
        "Content plan + texts in Premium package",
      ],
      popular: "Popular",
      plans: [
        { name: "Visual Light", price: "₽2,990", features: ["8 photos in unified style", "Square format 1:1", "For VK or Telegram"] },
        { name: "Visual Standard", price: "₽4,990", popular: true, features: ["12 photos in unified style", "Square 1:1 + stories 9:16", "2 promo banners", "For VK and Telegram"] },
        { name: "Visual Premium", price: "₽7,990", features: ["15 photos + 5 stories", "3 promo banners", "Monthly content plan", "Captions for each post", "Hashtags"] },
      ],
      orderBtn: "Order",
    },
    blog: {
      tag: "Streltsov Digital",
      title: "BLOG",
      sub: "Articles about design, AI and business",
      filters: ["All", "Design", "AI", "Marketplaces", "Cafe", "Branding", "Case", "Guide"],
      readMore: "Read →",
      minRead: "min",
      loadMore: "Load more articles",
    },
  },
};

type Translations = typeof translations.ru;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("ru");
  const t = translations[lang] as Translations;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used within LanguageProvider");
  return ctx;
}
